version: '3'
services:
  db:
    image: mariadb:latest
    command: --max_allowed_packet=32505856
    volumes:
      - ./mysql/runtime2:/var/lib/mysql
    env_file:
      - db.env
  app:
    image: matomo:4.15.1-fpm
    links:
      - db
    volumes:
      - ./matomo:/var/www/html
    env_file:
      - matomo.env
  web:
    image: nginx:latest
    volumes:
      - ./matomo:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    ports:
      - 127.0.0.1:8088:80
