version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - ./mysql/runtime2:/var/lib/mysql
    env_file:
      - db.env
  app:
    image: matomo:fpm
    links:
      - db
    volumes:
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
    env_file:
      - matomo.env
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    ports:
      - 127.0.0.1:8088:80
